apiVersion: v1
kind: Service
metadata:
  name: {{ include "arena.fullname" . }}
  labels:
    {{- include "arena.labels" . | nindent 4 }}
spec:
  ports:
  - port: 8080
    name: high
    protocol: TCP
    targetPort: 8080
  - port: 80
    name: low
    protocol: TCP
    targetPort: 8080
  selector:
    {{- include "arena.selectorLabels" . | nindent 4 }}
