apiVersion: v1
kind: Service
metadata:
  name: {{ include "arena.fullname" . }}
  labels:
    {{- include "arena.labels" . | nindent 4 }}
spec:
  ports:
  - port: 433
    name: low
    protocol: TCP
    targetPort: 8443
  selector:
    {{- include "arena.selectorLabels" . | nindent 4 }}
